# -*- coding: utf-8 -*-
"""Health Tracker OOP .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbrP8wODVphOESKBDx5ORfflqtDjxYGi
"""

# ===============================
# HEALTH TRACKER - OOP VERSION
# by Tanjim
# ===============================

import os
import csv
import requests
import matplotlib.pyplot as plt
from datetime import datetime


class HealthTracker:

    def __init__(self):
        self.name = ""
        self.age = 0
        self.gender = ""
        self.address = ""
        self.country = ""
        self.profile_file = ""
        self.temp_file = ""

    # ----------------------------
    # USER PROFILE SECTION
    # ----------------------------

    def create_or_load_profile(self):
        self.name = input("Enter your name: ").strip()
        self.profile_file = f"{self.name}_profile.txt"
        self.temp_file = f"{self.name}_temperature.csv"

        if os.path.exists(self.profile_file):
            print("\nProfile found. Loading details...\n")
            self.load_profile()
        else:
            print("\nCreating new profile...\n")
            self.create_profile()

    def create_profile(self):
        self.age = self.get_valid_age()
        self.gender = self.get_valid_gender()
        self.address = input("Enter your address: ").strip()
        self.country = input("Enter your country: ").strip()

        with open(self.profile_file, "w") as f:
            f.write(f"Name:{self.name}\n")
            f.write(f"Age:{self.age}\n")
            f.write(f"Gender:{self.gender}\n")
            f.write(f"Address:{self.address}\n")
            f.write(f"Country:{self.country}\n")

        print("\nProfile saved successfully!")

    def load_profile(self):
        with open(self.profile_file, "r") as f:
            lines = f.readlines()

        for line in lines:
            key, value = line.strip().split(":")
            if key == "Age":
                self.age = int(value)
            else:
                setattr(self, key.lower(), value)

        print(f"Welcome back {self.name}!")

    # ----------------------------
    # VALIDATION METHODS
    # ----------------------------

    def get_valid_age(self):
        while True:
            try:
                age = int(input("Enter your age: "))
                if 0 < age < 110:
                    return age
                else:
                    print("Invalid age. Try again.")
            except:
                print("Please enter a number.")

    def get_valid_gender(self):
        while True:
            gender = input("Enter gender (M/F): ").lower()
            if gender in ["m", "f"]:
                return "Male" if gender == "m" else "Female"
            else:
                print("Invalid input. Enter M or F.")

    def get_valid_date(self):
        while True:
            date = input("Enter date (YYYY-MM-DD): ")
            try:
                datetime.strptime(date, "%Y-%m-%d")
                return date
            except:
                print("Invalid date format.")

    # ----------------------------
    # TEMPERATURE SECTION
    # ----------------------------

    def enter_temperature(self):
        date = self.get_valid_date()

        while True:
            try:
                temp = float(input("Enter temperature in Celsius: "))
                break
            except:
                print("Enter valid temperature.")

        file_exists = os.path.exists(self.temp_file)

        with open(self.temp_file, "a", newline="") as file:
            writer = csv.writer(file)
            if not file_exists:
                writer.writerow(["Date", "Temperature"])
            writer.writerow([date, temp])

        print("Temperature saved successfully!")

        if temp > 37:
            print("\n⚠ WARNING: You have fever.")
            print("Please consult a doctor immediately.\n")

    # ----------------------------
    # GRAPH SECTION
    # ----------------------------

    def show_graph(self):
        if not os.path.exists(self.temp_file):
            print("No temperature records found.")
            return

        dates = []
        temps = []

        with open(self.temp_file, "r") as file:
            reader = csv.DictReader(file)
            for row in reader:
                dates.append(row["Date"])
                temps.append(float(row["Temperature"]))

        plt.figure()
        plt.plot(dates, temps)
        plt.xlabel("Date")
        plt.ylabel("Temperature (°C)")
        plt.title("Temperature Analysis")
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

    # ----------------------------
    # COVID STATISTICS (API BASED)
    # ----------------------------

    def check_covid_stats(self):
        country = input(f"Enter country (default {self.country}): ").strip()
        if not country:
            country = self.country

        url = f"https://disease.sh/v3/covid-19/countries/{country}"

        try:
            response = requests.get(url)
            data = response.json()

            print("\nCOVID-19 Statistics")
            print("----------------------")
            print("Country:", data["country"])
            print("Total Cases:", data["cases"])
            print("Today's Cases:", data["todayCases"])
            print("Total Deaths:", data["deaths"])
            print("Today's Deaths:", data["todayDeaths"])
            print("Recovered:", data["recovered"])
            print("Active:", data["active"])
            print("Critical:", data["critical"])
        except:
            print("Could not fetch data. Check country name.")

    # ----------------------------
    # PRECAUTIONS
    # ----------------------------

    def show_precautions(self):
        precautions = [
            "1. Wash hands regularly.",
            "2. Wear a mask.",
            "3. Maintain social distancing.",
            "4. Avoid crowded places.",
            "5. Get vaccinated."
        ]

        print("\nPrecautions:")
        for p in precautions:
            print(p)

    # ----------------------------
    # MAIN MENU
    # ----------------------------

    def run(self):
        self.create_or_load_profile()

        while True:
            print("\n==============================")
            print("1. Enter Temperature")
            print("2. Check COVID Stats")
            print("3. Show Temperature Graph")
            print("4. Show Precautions")
            print("5. Exit")
            print("==============================")

            choice = input("Select option: ")

            if choice == "1":
                self.enter_temperature()
            elif choice == "2":
                self.check_covid_stats()
            elif choice == "3":
                self.show_graph()
            elif choice == "4":
                self.show_precautions()
            elif choice == "5":
                print("Stay safe and healthy!")
                break
            else:
                print("Invalid choice.")


# ----------------------------
# PROGRAM START
# ----------------------------

if __name__ == "__main__":
    app = HealthTracker()
    app.run()